"""Your migration message

Revision ID: f3c1ed8231d5
Revises: 
Create Date: 2025-06-02 21:34:02.512992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3c1ed8231d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('foreign', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_cities_code'), 'cities', ['code'], unique=False)
    op.create_index(op.f('ix_cities_gk_id'), 'cities', ['gk_id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_uuid'), 'cities', ['uuid'], unique=True)
    op.create_table('products',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('display', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('foreign', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_products_count'), 'products', ['count'], unique=False)
    op.create_index(op.f('ix_products_display'), 'products', ['display'], unique=False)
    op.create_index(op.f('ix_products_gk_id'), 'products', ['gk_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_prefix'), 'products', ['prefix'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.create_table('promo_services',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('denomination', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_promo_services_code'), 'promo_services', ['code'], unique=False)
    op.create_index(op.f('ix_promo_services_denomination'), 'promo_services', ['denomination'], unique=False)
    op.create_index(op.f('ix_promo_services_description'), 'promo_services', ['description'], unique=False)
    op.create_index(op.f('ix_promo_services_gk_id'), 'promo_services', ['gk_id'], unique=False)
    op.create_index(op.f('ix_promo_services_name'), 'promo_services', ['name'], unique=False)
    op.create_index(op.f('ix_promo_services_uuid'), 'promo_services', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('gk_users',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('sber_id', sa.String(), nullable=True),
    sa.Column('gazprom_id', sa.String(), nullable=True),
    sa.Column('aeroflot_id', sa.String(), nullable=True),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('passes_amount', sa.Integer(), nullable=False),
    sa.Column('user_qr', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_gk_users_gk_user_id'), 'gk_users', ['gk_user_id'], unique=True)
    op.create_index(op.f('ix_gk_users_user_uuid'), 'gk_users', ['user_uuid'], unique=True)
    op.create_index(op.f('ix_gk_users_uuid'), 'gk_users', ['uuid'], unique=True)
    op.create_table('halls',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('admin_name', sa.String(), nullable=True),
    sa.Column('working_time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('htype_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('city_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('city_gk_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_uuid'], ['cities.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_halls_admin_name'), 'halls', ['admin_name'], unique=False)
    op.create_index(op.f('ix_halls_city'), 'halls', ['city'], unique=False)
    op.create_index(op.f('ix_halls_city_gk_id'), 'halls', ['city_gk_id'], unique=False)
    op.create_index(op.f('ix_halls_city_uuid'), 'halls', ['city_uuid'], unique=False)
    op.create_index(op.f('ix_halls_gk_id'), 'halls', ['gk_id'], unique=True)
    op.create_index(op.f('ix_halls_htype_id'), 'halls', ['htype_id'], unique=False)
    op.create_index(op.f('ix_halls_location'), 'halls', ['location'], unique=False)
    op.create_index(op.f('ix_halls_name'), 'halls', ['name'], unique=False)
    op.create_index(op.f('ix_halls_station_id'), 'halls', ['station_id'], unique=False)
    op.create_index(op.f('ix_halls_uuid'), 'halls', ['uuid'], unique=True)
    op.create_index(op.f('ix_halls_working_time'), 'halls', ['working_time'], unique=False)
    op.create_table('medias',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hall_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_id', sa.BigInteger(), nullable=False),
    sa.Column('hall_gk_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hall_uuid'], ['halls.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_medias_gk_id'), 'medias', ['gk_id'], unique=False)
    op.create_index(op.f('ix_medias_hall_gk_id'), 'medias', ['hall_gk_id'], unique=False)
    op.create_index(op.f('ix_medias_hall_uuid'), 'medias', ['hall_uuid'], unique=False)
    op.create_index(op.f('ix_medias_url'), 'medias', ['url'], unique=False)
    op.create_index(op.f('ix_medias_uuid'), 'medias', ['uuid'], unique=True)
    op.create_table('services',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hall_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gk_id', sa.BigInteger(), nullable=False),
    sa.Column('hall_gk_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hall_uuid'], ['halls.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_services_content'), 'services', ['content'], unique=False)
    op.create_index(op.f('ix_services_gk_id'), 'services', ['gk_id'], unique=False)
    op.create_index(op.f('ix_services_hall_gk_id'), 'services', ['hall_gk_id'], unique=False)
    op.create_index(op.f('ix_services_hall_uuid'), 'services', ['hall_uuid'], unique=False)
    op.create_index(op.f('ix_services_icon_url'), 'services', ['icon_url'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_service_type'), 'services', ['service_type'], unique=False)
    op.create_index(op.f('ix_services_text'), 'services', ['text'], unique=False)
    op.create_index(op.f('ix_services_uuid'), 'services', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_uuid'), table_name='services')
    op.drop_index(op.f('ix_services_text'), table_name='services')
    op.drop_index(op.f('ix_services_service_type'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_icon_url'), table_name='services')
    op.drop_index(op.f('ix_services_hall_uuid'), table_name='services')
    op.drop_index(op.f('ix_services_hall_gk_id'), table_name='services')
    op.drop_index(op.f('ix_services_gk_id'), table_name='services')
    op.drop_index(op.f('ix_services_content'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_medias_uuid'), table_name='medias')
    op.drop_index(op.f('ix_medias_url'), table_name='medias')
    op.drop_index(op.f('ix_medias_hall_uuid'), table_name='medias')
    op.drop_index(op.f('ix_medias_hall_gk_id'), table_name='medias')
    op.drop_index(op.f('ix_medias_gk_id'), table_name='medias')
    op.drop_table('medias')
    op.drop_index(op.f('ix_halls_working_time'), table_name='halls')
    op.drop_index(op.f('ix_halls_uuid'), table_name='halls')
    op.drop_index(op.f('ix_halls_station_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_name'), table_name='halls')
    op.drop_index(op.f('ix_halls_location'), table_name='halls')
    op.drop_index(op.f('ix_halls_htype_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_gk_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_city_uuid'), table_name='halls')
    op.drop_index(op.f('ix_halls_city_gk_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_city'), table_name='halls')
    op.drop_index(op.f('ix_halls_admin_name'), table_name='halls')
    op.drop_table('halls')
    op.drop_index(op.f('ix_gk_users_uuid'), table_name='gk_users')
    op.drop_index(op.f('ix_gk_users_user_uuid'), table_name='gk_users')
    op.drop_index(op.f('ix_gk_users_gk_user_id'), table_name='gk_users')
    op.drop_table('gk_users')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_promo_services_uuid'), table_name='promo_services')
    op.drop_index(op.f('ix_promo_services_name'), table_name='promo_services')
    op.drop_index(op.f('ix_promo_services_gk_id'), table_name='promo_services')
    op.drop_index(op.f('ix_promo_services_description'), table_name='promo_services')
    op.drop_index(op.f('ix_promo_services_denomination'), table_name='promo_services')
    op.drop_index(op.f('ix_promo_services_code'), table_name='promo_services')
    op.drop_table('promo_services')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_prefix'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_gk_id'), table_name='products')
    op.drop_index(op.f('ix_products_display'), table_name='products')
    op.drop_index(op.f('ix_products_count'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_cities_uuid'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_gk_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_code'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
